#stages:
#  - testing
#  - deploy
#  - develop
#  - test
#  - stage
#
#.testing:
#  stage: testing
#  image: masterglorious/ubuntu18.04-ansible-python3.8
#  before_script:
#    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
#    - eval $(ssh-agent -s)
#    - echo "{$SSH_PRIVATE_KEY}"
#    - echo "$CI_ENVIRONMENT_NAME"
#
#.build:
#  before_script:
#    - echo "$SSH_PRIVATE_KEY"
#
#testing:
#  extends: .testing
#  script:
#    - echo "${CONFIGS_TESTING}"
#  allow_failure: false
#  tags:
#    - sale-service
