version: '3.7'

services:
  sale-service-migration:
    build: .
    image: sale-service
    volumes:
      - .:/code
    working_dir: /code
    network_mode: "host"
    command: alembic upgrade head

  sale-service-api:
    image: sale-service
    volumes:
      - .:/code
    working_dir: /code
    network_mode: "host"
    expose:
      - "8005"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8005
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/sale-service/healthcheck"]
      interval: 30s
      timeout: 20s
      retries: 3