"""empty message

Revision ID: 6fa0c938518d
Revises: f5e0dca8688f
Create Date: 2020-12-16 14:25:43.357948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa0c938518d'
down_revision = 'f5e0dca8688f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
