"""empty message

Revision ID: 7038af0ff788
Revises: f28984f8a733
Create Date: 2020-12-16 09:41:50.986807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7038af0ff788'
down_revision = 'f28984f8a733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_staffteam_staff_id', table_name='staffteam')
    op.drop_table('staffteam')
    op.drop_index('ix_team_code', table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffteam',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name='staffteam_staff_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='staffteam_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='staffteam_pkey')
    )
    op.create_index('ix_staffteam_staff_id', 'staffteam', ['staff_id'], unique=True)
    op.create_table('team',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='team_pkey')
    )
    op.create_index('ix_team_code', 'team', ['code'], unique=True)
    # ### end Alembic commands ###
