"""create model team

Revision ID: 710550d16885
Revises: be1b6c5fa3ae
Create Date: 2020-12-15 10:15:13.326920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710550d16885'
down_revision = 'be1b6c5fa3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_code'), 'team', ['code'], unique=True)
    op.add_column('staff', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('staff', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('staff', sa.Column('team_id', sa.Integer(), nullable=True))
    op.drop_index('ix_staff_status', table_name='staff')
    op.create_foreign_key(None, 'staff', 'staff', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'staff', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.create_index('ix_staff_status', 'staff', ['status'], unique=False)
    op.drop_column('staff', 'team_id')
    op.drop_column('staff', 'parent_id')
    op.drop_column('staff', 'is_superuser')
    op.drop_index(op.f('ix_team_code'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
