"""empty message

Revision ID: f5e0dca8688f
Revises: 7038af0ff788
Create Date: 2020-12-16 09:50:25.945394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e0dca8688f'
down_revision = '7038af0ff788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('alias', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'alias')
    # ### end Alembic commands ###
